Chore, updates operator-sdk, check todos
belastingdienst/opr-paas pull request #1
Opened 2024-09-02 14:12 UTC by portly-halicore-76

Updates opr-sdk to comply with latest version upstream.

2024-09-02 14:21 UTC, hikarukin submitted a review, later dismissed

2024-09-02 14:27 UTC, devotional-phoenix-97 requested changes

2024-09-02 14:27 UTC, devotional-phoenix-97 commented on Dockerfile
> +COPY cmd/main.go cmd/main.go
operator-sdk (I guess this is the old operator convention) has this in /main.go
Seems like (as you emntioned) new convention is /cmd/main.go, but this is not inline with standard golang convention which would be /cmd/[folder]/main.go (where [folder] is a seperate folder for every binary to be built from this codebase).
CNPG seems to follow the GoLang convention (as they have /cmd/manager/main.go, and /cmd/kubectl-cnpg/main.go.
Let's use that convention and also move the cli stuff there too.
-  /cmd/manager/main.go (formerly /main.go)
-  /cmd/crypttool/main.go (formerly /cli/crypttool/main.go)
-  /cmd/webservice/main.go (formerly /cli/webservice/main.go, which will probably get its own repo).

2024-09-02 14:27 UTC, devotional-phoenix-97 commented on Dockerfile
> -COPY controllers/ controllers/
Deze code hebben we toch in de docker container nodig?

2024-09-02 14:28 UTC, portly-halicore-76 commented on Dockerfile
> +COPY cmd/main.go cmd/main.go
cmd/main.go is juist wat operator-sdk nu doet.

2024-09-03 07:26 UTC, portly-halicore-76 commented on Dockerfile
> +COPY cmd/main.go cmd/main.go
Done, eends

2024-09-03 07:29 UTC, hikarukin approved these changes

2024-09-03 07:31 UTC, hikarukin approved these changes

2024-09-03 07:35 UTC, merged