feat: Fix for issue 147 Name Suggestion for ClusterRole and ClusterRolebinding
belastingdienst/opr-paas pull request #149
Opened 2024-11-18 20:08 UTC by benoitschipper

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

Fixes: #147 

Feature PR for feature request 147

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

2024-11-18 20:11 UTC, portly-halicore-76 requested changes
Please update this role as well, this is not managed via kubebuilder, it's a one-off. https://github.com/belastingdienst/opr-paas/blob/main/manifests/rbac/leader_election_role_binding.yaml#L18

2024-11-18 20:15 UTC, benoitschipper commented
Will do

2024-11-18 20:21 UTC, benoitschipper commented
@portly-halicore-76 I checked and I can do that , do not see that this is being generated by the MakeFile. On the otherhand, I might then as well take the below with me:

- leader_election_role.yaml
- leader_election_role_binding.yaml
- service_account.yaml

and aas paas-* to them. And also re-update the ones I already committed.

Please let me know.

2024-11-19 13:36 UTC, portly-halicore-76 commented
> @portly-halicore-76 I checked and I can do that , do not see that this is being generated by the MakeFile. On the otherhand, I might then as well take the below with me:
> 
> * leader_election_role.yaml
> * leader_election_role_binding.yaml
> * service_account.yaml
> 
> and aas paas-* to them. And also re-update the ones I already committed.
> 
> Please let me know.

Please follow-up on this suggestion and specify the names in those yaml files as well.

2024-11-20 15:59 UTC, benoitschipper commented
Will do

2024-11-24 16:31 UTC, benoitschipper commented
Done

2024-11-24 16:39 UTC, benoitschipper commented
I assume the tests fail as it tries to deploy it with a service account that does not exist now. Do we need to also change the manifests/manager/opr-paas-deployment.yaml to the correct SA?

2024-11-24 18:39 UTC, benoitschipper commented
Suggest to change the e2e test, if we also want to change the deployment name: else the e2e test fails. What you say?

2024-11-25 08:56 UTC, portly-halicore-76 commented
> Suggest to change the e2e test, if we also want to change the deployment name: else the e2e test fails. What you say?

Great suggestion, please commit. You just have to update the deployments name in de e2e-tests-against-deployment in GA workflow. Than it should work.

Also please rebase on main to enable merging.

2024-11-25 10:38 UTC, benoitschipper commented
Will do

2024-11-26 15:20 UTC, benoitschipper commented
Should be good now

2024-11-26 18:24 UTC, portly-halicore-76 commented on manifests/manager/opr-paas-deployment.yaml
>      app.kubernetes.io/instance: controller-manager
```suggestion
    app.kubernetes.io/instance: paas-controller-manager
```

2024-11-27 08:38 UTC, portly-halicore-76 approved these changes
Thanks you for your contribution.

2024-11-27 08:38 UTC, merged