Refactor wait step in e2e tests
belastingdienst/opr-paas pull request #44
Opened 2024-09-18 09:54 UTC by AxiomaticFixedChimpanzee

Use the e2e framework's mechanism for polling k8s for changes, as shown in
https://github.com/kubernetes-sigs/e2e-framework/tree/v0.4.0/examples/wait_for_resources

This replaces the previous implementation where each test would need to call `time.Sleep()` to wait an arbitrary amount of time for the operator to apply updates, which is sensitive to environment (a resource-constrained test environment might take longer to apply changes, meaning we need to tune the test suite for the lowest common denominator).

The `wait.For()` functionality from `sigs.k8s.io/e2e-framework` still waits an arbitrary (configurable) amount of time, but implements polling and timeouts and is generally more robust. This PR defines a few helper functions for synchronously creating, deleting, or updating k8s resources via the use of `wait.For()`.

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [x] Other (please describe): end-to-end test refactor

2024-09-18 14:20 UTC, portly-halicore-76 requested changes

2024-09-18 14:20 UTC, portly-halicore-76 commented on test/e2e/util.go
> +	if err := wait.For(waitCond, wait.WithContext(ctx), wait.WithInterval(waitInterval)); err != nil {
For each wait.For in the tests, please use the option to set a escape as we could otherwise be waiting until.... 
see: https://github.com/kubernetes-sigs/e2e-framework/blob/main/examples/wait_for_resources/wait_test.go#L62

2024-09-18 14:24 UTC, AxiomaticFixedChimpanzee commented on test/e2e/util.go
> +	if err := wait.For(waitCond, wait.WithContext(ctx), wait.WithInterval(waitInterval)); err != nil {
The default timeout is set at 5 minutes, should I do 1 minute perhaps?

2024-09-18 14:25 UTC, portly-halicore-76 commented on test/e2e/util.go
> +	if err := wait.For(waitCond, wait.WithContext(ctx), wait.WithInterval(waitInterval)); err != nil {
Perfect to start with! Wasn't aware of a sane default, excuse me.

2024-09-18 14:53 UTC, portly-halicore-76 commented on test/e2e/util.go
> +	waitCond := conditions.New(resources).ResourceMatch(obj, func(object k8s.Object) bool {
The condition stated here, is wait until kubernetes has processed the update request. However, we would like to continue with our tests, thus wait until, the Paas operator has processed the reconciliation of the new version of the resource. This can be checked by the status block of the Paas containing the message from: https://github.com/belastingdienst/opr-paas/blob/main/internal/controller/paas_controller.go#L169

2024-09-18 14:56 UTC, portly-halicore-76 commented on test/e2e/util.go
> +		ResourceMatch(obj, func(object k8s.Object) bool { return true })
The same principle should apply here, as stated in the comment below. We should wait until the operator has reconciled the Paas successfully before starting assessing its outcome.

2024-09-18 14:58 UTC, portly-halicore-76 submitted a review, later dismissed
Great work! Had some concerns about the wait conditions which are in my opinion different than where we really should wait for during our tests. See comments.

2024-09-23 09:00 UTC, AxiomaticFixedChimpanzee commented on test/e2e/util.go
> +	waitCond := conditions.New(resources).ResourceMatch(obj, func(object k8s.Object) bool {
I was unsure about just checking versions, this makes a lot more sense. I've updated the functions to be Paas-specific and check for that status message.

2024-09-23 09:21 UTC, hikarukin approved these changes
LGTM

2024-09-23 09:25 UTC, merged